/*
 * This code is generated by blanco Framework.
 */
package blanco.meta2xml.valueobject;

import junit.framework.TestCase;

/**
 * クラス[BlancoMeta2XmlProcessStructure]の単体試験クラス。<br>
 * このクラスはJUnitのテストケースです。
 */
public class BlancoMeta2XmlProcessStructureTest extends TestCase {
    /**
     * フィールド[name]の単体試験メソッド<br>
     * このメソッドでは、クラス[BlancoMeta2XmlProcessStructure]のフィールド[name] ([java.lang.String]型)について自動試験を行います。<br>
     *
     * @throws Exception
     */
    public void testName() throws Exception {
        // 単体試験の中で利用するValueObjectインスタンスを生成します。
        final BlancoMeta2XmlProcessStructure valueObject = new BlancoMeta2XmlProcessStructure();

        // ValueObjectのフィールドに対してデフォルト値が設定されていない場合の試験を行います。
        assertEquals("[正常]デフォルト値: クラスバリューオブジェクト[BlancoMeta2XmlProcessStructure]のインスタンスを生成した直後に、フィールド[name]の値を取得するとnullが得られることの確認", null, valueObject.getName());

        // 文字列の試験を行います。
        valueObject.setName("文字列データ");
        assertEquals("[正常]挙動: クラスバリューオブジェクト[BlancoMeta2XmlProcessStructure]のインスタンスに対して、フィールド[name]のセッターメソッドを使って文字列[文字列データ]を設定すると、フィールド[name]のゲッターメソッドを使って[文字列データ]が取得できることの確認", "文字列データ", valueObject.getName());

        // nullの試験を行います。
        valueObject.setName(null);
        assertEquals("[境界]null値: クラスバリューオブジェクト[BlancoMeta2XmlProcessStructure]のインスタンスに対して、フィールド[name]のセッターメソッドを使ってnullをセットした場合には、フィールド[name]のゲッターメソッドを使ってnullが取得できることの確認", null, valueObject.getName());

        // セッターで与えたインスタンスとゲッターで取得したインスタンスとが一致することを試験します。
        final String strInstanceCheck = "文字列データ２";
        valueObject.setName(strInstanceCheck);
        assertTrue("[正常]挙動: クラスバリューオブジェクト[BlancoMeta2XmlProcessStructure]のインスタンスに対して、フィールド[name]のセッターメソッドを使ってjava.lang.Stringオブジェクトのインスタンスを設定すると、フィールド[name]のゲッターメソッドを使って同一のjava.lang.Stringオブジェクトのインスタンスが取得されることの確認", strInstanceCheck == valueObject.getName());

    }

    /**
     * フィールド[package]の単体試験メソッド<br>
     * このメソッドでは、クラス[BlancoMeta2XmlProcessStructure]のフィールド[package] ([java.lang.String]型)について自動試験を行います。<br>
     *
     * @throws Exception
     */
    public void testPackage() throws Exception {
        // 単体試験の中で利用するValueObjectインスタンスを生成します。
        final BlancoMeta2XmlProcessStructure valueObject = new BlancoMeta2XmlProcessStructure();

        // ValueObjectのフィールドに対してデフォルト値が設定されていない場合の試験を行います。
        assertEquals("[正常]デフォルト値: クラスバリューオブジェクト[BlancoMeta2XmlProcessStructure]のインスタンスを生成した直後に、フィールド[package]の値を取得するとnullが得られることの確認", null, valueObject.getPackage());

        // 文字列の試験を行います。
        valueObject.setPackage("文字列データ");
        assertEquals("[正常]挙動: クラスバリューオブジェクト[BlancoMeta2XmlProcessStructure]のインスタンスに対して、フィールド[package]のセッターメソッドを使って文字列[文字列データ]を設定すると、フィールド[package]のゲッターメソッドを使って[文字列データ]が取得できることの確認", "文字列データ", valueObject.getPackage());

        // nullの試験を行います。
        valueObject.setPackage(null);
        assertEquals("[境界]null値: クラスバリューオブジェクト[BlancoMeta2XmlProcessStructure]のインスタンスに対して、フィールド[package]のセッターメソッドを使ってnullをセットした場合には、フィールド[package]のゲッターメソッドを使ってnullが取得できることの確認", null, valueObject.getPackage());

        // セッターで与えたインスタンスとゲッターで取得したインスタンスとが一致することを試験します。
        final String strInstanceCheck = "文字列データ２";
        valueObject.setPackage(strInstanceCheck);
        assertTrue("[正常]挙動: クラスバリューオブジェクト[BlancoMeta2XmlProcessStructure]のインスタンスに対して、フィールド[package]のセッターメソッドを使ってjava.lang.Stringオブジェクトのインスタンスを設定すると、フィールド[package]のゲッターメソッドを使って同一のjava.lang.Stringオブジェクトのインスタンスが取得されることの確認", strInstanceCheck == valueObject.getPackage());

    }

    /**
     * フィールド[description]の単体試験メソッド<br>
     * このメソッドでは、クラス[BlancoMeta2XmlProcessStructure]のフィールド[description] ([java.lang.String]型)について自動試験を行います。<br>
     *
     * @throws Exception
     */
    public void testDescription() throws Exception {
        // 単体試験の中で利用するValueObjectインスタンスを生成します。
        final BlancoMeta2XmlProcessStructure valueObject = new BlancoMeta2XmlProcessStructure();

        // ValueObjectのフィールドに対してデフォルト値が設定されていない場合の試験を行います。
        assertEquals("[正常]デフォルト値: クラスバリューオブジェクト[BlancoMeta2XmlProcessStructure]のインスタンスを生成した直後に、フィールド[description]の値を取得するとnullが得られることの確認", null, valueObject.getDescription());

        // 文字列の試験を行います。
        valueObject.setDescription("文字列データ");
        assertEquals("[正常]挙動: クラスバリューオブジェクト[BlancoMeta2XmlProcessStructure]のインスタンスに対して、フィールド[description]のセッターメソッドを使って文字列[文字列データ]を設定すると、フィールド[description]のゲッターメソッドを使って[文字列データ]が取得できることの確認", "文字列データ", valueObject.getDescription());

        // nullの試験を行います。
        valueObject.setDescription(null);
        assertEquals("[境界]null値: クラスバリューオブジェクト[BlancoMeta2XmlProcessStructure]のインスタンスに対して、フィールド[description]のセッターメソッドを使ってnullをセットした場合には、フィールド[description]のゲッターメソッドを使ってnullが取得できることの確認", null, valueObject.getDescription());

        // セッターで与えたインスタンスとゲッターで取得したインスタンスとが一致することを試験します。
        final String strInstanceCheck = "文字列データ２";
        valueObject.setDescription(strInstanceCheck);
        assertTrue("[正常]挙動: クラスバリューオブジェクト[BlancoMeta2XmlProcessStructure]のインスタンスに対して、フィールド[description]のセッターメソッドを使ってjava.lang.Stringオブジェクトのインスタンスを設定すると、フィールド[description]のゲッターメソッドを使って同一のjava.lang.Stringオブジェクトのインスタンスが取得されることの確認", strInstanceCheck == valueObject.getDescription());

    }

    /**
     * フィールド[fileDescription]の単体試験メソッド<br>
     * このメソッドでは、クラス[BlancoMeta2XmlProcessStructure]のフィールド[fileDescription] ([java.lang.String]型)について自動試験を行います。<br>
     *
     * @throws Exception
     */
    public void testFileDescription() throws Exception {
        // 単体試験の中で利用するValueObjectインスタンスを生成します。
        final BlancoMeta2XmlProcessStructure valueObject = new BlancoMeta2XmlProcessStructure();

        // ValueObjectのフィールドに対してデフォルト値が設定されている場合の試験を行います。
        assertEquals("[正常]デフォルト値: クラスバリューオブジェクト[BlancoMeta2XmlProcessStructure]のインスタンスを生成した直後に、フィールド[fileDescription]の値を取得すると[このクラスはblancoValueObjectにより自動生成されました。]が得られることの確認", "このクラスはblancoValueObjectにより自動生成されました。", valueObject.getFileDescription());

        // 文字列の試験を行います。
        valueObject.setFileDescription("文字列データ");
        assertEquals("[正常]挙動: クラスバリューオブジェクト[BlancoMeta2XmlProcessStructure]のインスタンスに対して、フィールド[fileDescription]のセッターメソッドを使って文字列[文字列データ]を設定すると、フィールド[fileDescription]のゲッターメソッドを使って[文字列データ]が取得できることの確認", "文字列データ", valueObject.getFileDescription());

        // nullの試験を行います。
        valueObject.setFileDescription(null);
        assertEquals("[境界]null値: クラスバリューオブジェクト[BlancoMeta2XmlProcessStructure]のインスタンスに対して、フィールド[fileDescription]のセッターメソッドを使ってnullをセットした場合には、フィールド[fileDescription]のゲッターメソッドを使ってnullが取得できることの確認", null, valueObject.getFileDescription());

        // セッターで与えたインスタンスとゲッターで取得したインスタンスとが一致することを試験します。
        final String strInstanceCheck = "文字列データ２";
        valueObject.setFileDescription(strInstanceCheck);
        assertTrue("[正常]挙動: クラスバリューオブジェクト[BlancoMeta2XmlProcessStructure]のインスタンスに対して、フィールド[fileDescription]のセッターメソッドを使ってjava.lang.Stringオブジェクトのインスタンスを設定すると、フィールド[fileDescription]のゲッターメソッドを使って同一のjava.lang.Stringオブジェクトのインスタンスが取得されることの確認", strInstanceCheck == valueObject.getFileDescription());

    }

    /**
     * フィールド[convertDefFile]の単体試験メソッド<br>
     * このメソッドでは、クラス[BlancoMeta2XmlProcessStructure]のフィールド[convertDefFile] ([java.lang.String]型)について自動試験を行います。<br>
     *
     * @throws Exception
     */
    public void testConvertDefFile() throws Exception {
        // 単体試験の中で利用するValueObjectインスタンスを生成します。
        final BlancoMeta2XmlProcessStructure valueObject = new BlancoMeta2XmlProcessStructure();

        // ValueObjectのフィールドに対してデフォルト値が設定されていない場合の試験を行います。
        assertEquals("[正常]デフォルト値: クラスバリューオブジェクト[BlancoMeta2XmlProcessStructure]のインスタンスを生成した直後に、フィールド[convertDefFile]の値を取得するとnullが得られることの確認", null, valueObject.getConvertDefFile());

        // 文字列の試験を行います。
        valueObject.setConvertDefFile("文字列データ");
        assertEquals("[正常]挙動: クラスバリューオブジェクト[BlancoMeta2XmlProcessStructure]のインスタンスに対して、フィールド[convertDefFile]のセッターメソッドを使って文字列[文字列データ]を設定すると、フィールド[convertDefFile]のゲッターメソッドを使って[文字列データ]が取得できることの確認", "文字列データ", valueObject.getConvertDefFile());

        // nullの試験を行います。
        valueObject.setConvertDefFile(null);
        assertEquals("[境界]null値: クラスバリューオブジェクト[BlancoMeta2XmlProcessStructure]のインスタンスに対して、フィールド[convertDefFile]のセッターメソッドを使ってnullをセットした場合には、フィールド[convertDefFile]のゲッターメソッドを使ってnullが取得できることの確認", null, valueObject.getConvertDefFile());

        // セッターで与えたインスタンスとゲッターで取得したインスタンスとが一致することを試験します。
        final String strInstanceCheck = "文字列データ２";
        valueObject.setConvertDefFile(strInstanceCheck);
        assertTrue("[正常]挙動: クラスバリューオブジェクト[BlancoMeta2XmlProcessStructure]のインスタンスに対して、フィールド[convertDefFile]のセッターメソッドを使ってjava.lang.Stringオブジェクトのインスタンスを設定すると、フィールド[convertDefFile]のゲッターメソッドを使って同一のjava.lang.Stringオブジェクトのインスタンスが取得されることの確認", strInstanceCheck == valueObject.getConvertDefFile());

    }

    /**
     * フィールド[inputFileExt]の単体試験メソッド<br>
     * このメソッドでは、クラス[BlancoMeta2XmlProcessStructure]のフィールド[inputFileExt] ([java.lang.String]型)について自動試験を行います。<br>
     *
     * @throws Exception
     */
    public void testInputFileExt() throws Exception {
        // 単体試験の中で利用するValueObjectインスタンスを生成します。
        final BlancoMeta2XmlProcessStructure valueObject = new BlancoMeta2XmlProcessStructure();

        // ValueObjectのフィールドに対してデフォルト値が設定されている場合の試験を行います。
        assertEquals("[正常]デフォルト値: クラスバリューオブジェクト[BlancoMeta2XmlProcessStructure]のインスタンスを生成した直後に、フィールド[inputFileExt]の値を取得すると[.xls]が得られることの確認", ".xls", valueObject.getInputFileExt());

        // 文字列の試験を行います。
        valueObject.setInputFileExt("文字列データ");
        assertEquals("[正常]挙動: クラスバリューオブジェクト[BlancoMeta2XmlProcessStructure]のインスタンスに対して、フィールド[inputFileExt]のセッターメソッドを使って文字列[文字列データ]を設定すると、フィールド[inputFileExt]のゲッターメソッドを使って[文字列データ]が取得できることの確認", "文字列データ", valueObject.getInputFileExt());

        // nullの試験を行います。
        valueObject.setInputFileExt(null);
        assertEquals("[境界]null値: クラスバリューオブジェクト[BlancoMeta2XmlProcessStructure]のインスタンスに対して、フィールド[inputFileExt]のセッターメソッドを使ってnullをセットした場合には、フィールド[inputFileExt]のゲッターメソッドを使ってnullが取得できることの確認", null, valueObject.getInputFileExt());

        // セッターで与えたインスタンスとゲッターで取得したインスタンスとが一致することを試験します。
        final String strInstanceCheck = "文字列データ２";
        valueObject.setInputFileExt(strInstanceCheck);
        assertTrue("[正常]挙動: クラスバリューオブジェクト[BlancoMeta2XmlProcessStructure]のインスタンスに対して、フィールド[inputFileExt]のセッターメソッドを使ってjava.lang.Stringオブジェクトのインスタンスを設定すると、フィールド[inputFileExt]のゲッターメソッドを使って同一のjava.lang.Stringオブジェクトのインスタンスが取得されることの確認", strInstanceCheck == valueObject.getInputFileExt());

    }

    /**
     * フィールド[outputFileExt]の単体試験メソッド<br>
     * このメソッドでは、クラス[BlancoMeta2XmlProcessStructure]のフィールド[outputFileExt] ([java.lang.String]型)について自動試験を行います。<br>
     *
     * @throws Exception
     */
    public void testOutputFileExt() throws Exception {
        // 単体試験の中で利用するValueObjectインスタンスを生成します。
        final BlancoMeta2XmlProcessStructure valueObject = new BlancoMeta2XmlProcessStructure();

        // ValueObjectのフィールドに対してデフォルト値が設定されている場合の試験を行います。
        assertEquals("[正常]デフォルト値: クラスバリューオブジェクト[BlancoMeta2XmlProcessStructure]のインスタンスを生成した直後に、フィールド[outputFileExt]の値を取得すると[.xml]が得られることの確認", ".xml", valueObject.getOutputFileExt());

        // 文字列の試験を行います。
        valueObject.setOutputFileExt("文字列データ");
        assertEquals("[正常]挙動: クラスバリューオブジェクト[BlancoMeta2XmlProcessStructure]のインスタンスに対して、フィールド[outputFileExt]のセッターメソッドを使って文字列[文字列データ]を設定すると、フィールド[outputFileExt]のゲッターメソッドを使って[文字列データ]が取得できることの確認", "文字列データ", valueObject.getOutputFileExt());

        // nullの試験を行います。
        valueObject.setOutputFileExt(null);
        assertEquals("[境界]null値: クラスバリューオブジェクト[BlancoMeta2XmlProcessStructure]のインスタンスに対して、フィールド[outputFileExt]のセッターメソッドを使ってnullをセットした場合には、フィールド[outputFileExt]のゲッターメソッドを使ってnullが取得できることの確認", null, valueObject.getOutputFileExt());

        // セッターで与えたインスタンスとゲッターで取得したインスタンスとが一致することを試験します。
        final String strInstanceCheck = "文字列データ２";
        valueObject.setOutputFileExt(strInstanceCheck);
        assertTrue("[正常]挙動: クラスバリューオブジェクト[BlancoMeta2XmlProcessStructure]のインスタンスに対して、フィールド[outputFileExt]のセッターメソッドを使ってjava.lang.Stringオブジェクトのインスタンスを設定すると、フィールド[outputFileExt]のゲッターメソッドを使って同一のjava.lang.Stringオブジェクトのインスタンスが取得されることの確認", strInstanceCheck == valueObject.getOutputFileExt());

    }

    /**
     *
     * @throws Exception
     */
    public void testToString() throws Exception {
        final BlancoMeta2XmlProcessStructure valueObject = new BlancoMeta2XmlProcessStructure();
        System.out.println(valueObject.toString());
    }
}
